#!/usr/bin/env bash
# install atom packages

# core packages
apm install \
    platformio-ide-terminal \
    highlight-selected \
    minimap \
    minimap-highlight-selected \
    file-icons \
    tree-view-scope-lines

# linter / languages
apm install \
    file-types \
    language-cmake \
    language-docker \
    language-protobuf \
    linter-solidity

# misc
apm install \
    structure-view \
    minimap-git-diff \
    activate-power-mode
